### ISSUE TITLE
g!setStatus command ain't working.

### ISSUE THREAD

**Issue by MaanasNair** [TheGingerCo/ginger-bot#1]
Hey, I loved the bot but, there's this problem i.e, when we write `g!setStatus` or `g!setStatus online` it doesn't give a response. I think we need a response even if the command fails..

![IMG_20210228_120513.jpg](https://user-images.githubusercontent.com/63333626/109410009-4054a100-79bd-11eb-98c7-82a0f75a96b1.jpg)

It should display an error message like this:
```
Sorry, you're not eligible to use this command..
```
Or something else.

**Comment by 0xGamer** [comment]
Hey there, we will be adding error handling and error responses soon.
